# Generated by Django 4.2.5 on 2023-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(default="", max_length=255, verbose_name="Предмет"),
        ),
    ]
